version: '3'
services:
  app:
    image: golang
    volumes:
      - .:/go/src/app
    entrypoint: /bin/bash
    depends_on:
      - db
  db:
    image: postgres
    environment:
     - POSTGRES_DB=dev
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
