version: '3'
services:
  app:
    image: golang
    volumes:
      - .:/go/src/github.com/mauricioklein/go-url-shortner
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_DATABASE=dev
    entrypoint: /bin/bash
    depends_on:
      - db
      - redis
  prod:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_DATABASE=dev
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
  redis:
    image: redis
    ports:
      - 6379:6379
