version: '3'
services:
  app:
    image: golang
    volumes:
      - .:/go/src/github.com/mauricioklein/go-url-shortner
    ports:
      - 8080:8080
    entrypoint: /bin/bash
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
