version: '3'
services:
  dev:
    image: golang
    volumes:
      - .:/go/src/github.com/mauricioklein/go-url-shortner
    working_dir: /go/src/github.com/mauricioklein/go-url-shortner
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_DATABASE=dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    entrypoint: /bin/bash
    depends_on:
      - db
      - redis
  
  app:
    build: .
    ports:
      - 8080
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_DATABASE=dev
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
  
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
  
  redis:
    image: redis
    ports:
      - 6379:6379
  
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
